branch-defaults:
  default:
    environment: devel
    group_suffix: null
global:
  application_name: AlexDegterov-bff-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: rs
  repository: null
  sc: null
  workspace_type: Application
